language: node_js
node_js: "8.9.4"
git:
   depth: 9999999
script: 
  - yarn format:verify
  - yarn lint
  - yarn test
deploy:
  - provider: azure_web_apps
    verbose: true
    site: register-a-food-business-dev
    on: 
      branch: develop
  - provider: azure_web_apps
    verbose: true
    site: register-a-food-business-dev
    slot: register-a-food-business-dev-double
    on: 
      branch: develop
  - provider: azure_web_apps
    verbose: true
    site: TEST-REGISTER-A-FOOD-BUSINESS
    on: 
      branch: master