language: node_js
node_js: "8.9.4"
git:
   depth: 9999999
stages:
  - name: dev build
    if: (branch != master) AND (branch != release) AND (branch != develop)
  - name: dev build and deploy
    if: branch = develop
  - name: test build and deploy
    if: (branch = develop) AND (type != pull_request)
  - name: staging deploy
    if: branch = release
  - name: prod deploy
    if: branch = master
jobs:
  include:
    - stage: dev build
      script:
        - yarn format:verify
        - yarn lint
        - yarn test:ci
    - stage: dev build and deploy
      script:
        - yarn format:verify
        - yarn lint
        - yarn test:ci
      deploy:
        - provider: azure_web_apps
          verbose: true
          site: dev-register-a-food-business
        - provider: azure_web_apps
          verbose: true
          site: dev-register-a-food-business
          slot: dev-register-a-food-business-double
    - stage: test build and deploy
      script:
        - yarn test:integration
      deploy:
        - provider: azure_web_apps
          verbose: true
          site: test-register-a-food-business
        - provider: azure_web_apps
          verbose: true
          site: test-register-a-food-business
          slot: test-register-a-food-business-double
    - stage: staging deploy
      script: echo "No tests to run"
      deploy:
        - provider: azure_web_apps
          verbose: true
          site: staging-register-a-food-business
    - stage: prod deploy
      script: echo "No tests to run"
      deploy:
        - provider: azure_web_apps
          verbose: true
          site: prod-register-a-food-business
          slot: prod-register-a-food-business-double