language: node_js
node_js:
- "8.9.4"
git:
   depth: 9999999
before_deploy: "next build"
deploy:
- provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on: feature/travis-deploy
  site: register-a-food-business-dev