# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: npm i -g yarn
  displayName: 'yarn install'

- script: yarn
  displayName: 'Install node_modules'

- script: yarn format:verify
  displayName: 'Format'

- script: yarn lint
  displayName: 'Lint'

- script: yarn test:ci
  displayName: 'Unit tests'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1