# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.14'
    
  - script: npm -v
    displayName: "Npm version"

  - script: yarn
    displayName: "Install dependencies"

  - script: yarn format:verify
    displayName: "Format"

  - script: yarn lint
    displayName: "Lint"

  - script: yarn test:ci
    displayName: "Unit tests"
    failOnStderr: false

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFile: ./reports/TEST-unit.xml
      testRunTitle: Unit tests
      mergeTestResults: false

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage/lcov-report"

  - script: yarn test:integration
    displayName: "Integration tests"

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFile: ./reports/TEST-integration.xml
      testRunTitle: Integration tests
      mergeTestResults: false

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonarcloud'
      organization: 'fsa'
      scannerMode: 'CLI'
      configMode: 'file'
      
  - task: SonarCloudAnalyze@1
  
  - script: yarn --production
    displayName: Prune dev dependencies

  - script: rm -rf coverage reports .vs .vscode docs src/__tests__
    displayName: Remove unnecessary folders

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
