name: E2E, UI Test
run-name: E2E, UI Test (${{ inputs.environment  }})
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        default: staging

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: choice
        required: true
        default: staging
        options:
          - staging
          - test

jobs:
  e2e_ui_test:
    name: E2E, UI Test
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      RELEASE_RELEASENAME: Release-${{ github.run_number }}
      BASE_URL: ${{ fromJSON('{"staging":"https://staging-register.food.gov.uk/new/","test":"https://test-register-a-food-business.azurewebsites.net/new/"}')[inputs.environment] }}
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
      QA_KEY: ${{ secrets.QA_KEY }}

    steps:
      - run: echo 'e2e, ui test'
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: FoodStandardsAgency/register-a-food-business-UI-tests
          ref: ${{ vars.UI_TESTS_BRANCH }}

      - name: Use Node.js 22.14
        uses: actions/setup-node@v1
        with:
          node-version: 22.14

      - name: Npm version
        run: npm -v

      - name: Install
        run: npm install

      - name: E2E Test
        if: inputs.environment == 'staging'
        run: npm run test:browserstack:e2e

      - name: Publish E2E Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && inputs.environment == 'staging'
        with:
          junit_files: ./reports/WDIO*.xml
          check_name: "E2E Test Results"

      - name: Remove E2E Test Results
        if: inputs.environment == 'staging'
        run: rm -rf ./reports/WDIO*.xml

      - name: Admin Portal Test
        if: inputs.environment == 'test'
        run: npm run test:browserstack:adminportal

      - name: Publish Admin Portal Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && inputs.environment == 'test'
        with:
          junit_files: ./reports/WDIO*.xml
          check_name: "Admin Portal Test Results"

      - name: Remove Admin Portal Test Results
        if: inputs.environment == 'test'
        run: rm -rf ./reports/WDIO*.xml

      - name: UI Test
        run: npm run test:browserstack:ui

      - name: Publish UI Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: ./reports/WDIO*.xml
          check_name: "UI Test Results"
